config/routes.rb
Tagenger::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :tags, only: [:create, :destroy]
  resources :users do
    resources :tags do
      member do
        delete :remove_user_tag
      end
    end
  end

  root to: 'users#new'
  #'/ui' to: 'ui#index'   # This was causing a redirect loop on Heroku

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new', 		via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/faq',     to: 'static_pages#faq', via: 'get'
  match '/submit',  to: 'messages#new',     via: 'get'

  # UI routes
  match '/ui',      to: 'ui#index',         via: 'get'
  get 'ui(/:action)', controller: 'ui'
  
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :first_name, presence: true, 
												 length: { maximum: 50 }
	validates :last_initial, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
										format: { with: VALID_EMAIL_REGEX }, 
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6}
	validates :tndcheck, presence: true

	has_many :user_tags
	has_many :tags, through: :user_tags

	has_many :messages


	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  # Call this with current_user.add_tag!(tag_number)
  # TODO: Determine if this should be add_tag! and create!
  def add_tag(tag_number)
  	user_tags.create(tag_id: Tag.find_by_tag_number(tag_number).id)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    if current_user
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Tagenger!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @tag = Tag.new
    @user = User.find(params[:id])
    @received_messages = []
    @user.tags.each do |tag|
      @received_messages += Message.find_all_by_tag_number(tag.tag_number)
    end
    # Sorts @received_messages by created_at date
    @received_messages.sort! {|a,b| b.created_at <=> a.created_at }
    @sent_messages = @user.messages
    # Another way to sort messages. sort! wasn't working for some reason
    @sent_messages = @sent_messages.order("created_at DESC")
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_initial, :email, :password,
                                   :password_confirmation, :tndcheck)
    end

    # before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
	<%= link_to user.first_name, user %>
	<% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_initial %>
      <%= f.text_field :last_initial %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :tndcheck %>
      <%= f.check_box :tndcheck %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!-- TODO: Fix entire index view -->
<% provide(:title, 'All users') %>
<h1>All users</h1>

<!-- TODO: Format pagination -->
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
      <%= render user %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<!-- not signed in -->

<div class="landing-top">
  <h1>Tagenger</h1><h3>leave messages for drivers</h3>
</div>

  <div class="landing-middle">
    <section id="sign-up" class="clearfix">

      <div class="col-sm-4">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <h4 class="small-margin text-left"> Sign Up </h4>
          
          <%= f.text_field :first_name, class:"form-control input-lg small-margin", placeholder:"First Name"  %>
          <%= f.text_field :last_initial, class:"form-control input-lg small-margin", placeholder:"Last Initial" %>
          <%= f.text_field :email, class:"form-control input-lg small-margin", placeholder:"Email" %>
          <%= f.password_field :password, class:"form-control input-lg small-margin", placeholder:"Password"  %>
          <%= f.password_field :password_confirmation, class:"form-control input-lg small-margin", placeholder:"Password Confirmation"  %>

          <%= f.label :tndcheck %>
          <%= f.check_box :tndcheck %>

          <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
       
      <div class="col-sm-6">
        <h4 class="text-left">Already a member? <a href="">Sign In</a></h4>
        <h2 class="text-left">Tagenger allows you to</h2>
        <ul id="landing-bullets" class="text-left">
          <li>Leave messages for other car owners anonymously.</li>
          <li>Receive messages from other drivers.</li>
        </ul>
      </div>
    </section><!--subscribe--> 

</div>

app/views/users/show.html.erb
<!-- TODO: Add a button that forwards to submit_path -->
<% provide(:title, @user.first_name) %>
<div class="row">
	<aside class="col-md-2 left-pad">
		<h3><%= @user.first_name %> <%= @user.last_initial %></h3>
		<%= link_to "delete profile", '#' %>
		<h3>Stats</h3>
		<p>
			<%= @sent_messages.count %> sent <%= 'message'.pluralize(@sent_messages.count) %>
		</p>
		<p>
			<%= @received_messages.count %> received <%= 'message'.pluralize(@received_messages.count) %>
		</p>
		<p>
			Created <%= time_ago_in_words(@user.created_at) %> ago.
		</p>
		<h3>My Tags: </h3>
		<% @user.tags.each do |tag| %> 
			<p><%= tag.tag_number %>
			<% if current_user?(@user) %>
				<%= link_to "X", remove_user_tag_user_tag_path(@user, tag), method: :delete %>
			<% end %>
			</p>
		<% end %>

		<h5>Add a Tag</h5>
		<%# Add state selector here as well and parse it in tags controller %>
		<%= form_for @tag do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.select(:tag_state, options_for_select(state_arr), {:selected => @temp, include_blank: "What State?"}, { class: "form-control"}) %>
			<%= f.text_field :tag_number, placeholder: "Tag Number" %>

			<%= f.submit "Add", class: "btn btn-large btn-primary" %>
		<% end %>

	</aside>
	<div class="col-md-7 left-pad">
		<h3>Sent Messages</h3>
		<% if @sent_messages.count == 0 %>
			You haven't sent any messages! Go ahead, <%= link_to 'send some out', submit_path %>!
		<% else %>
			<% @sent_messages.each do |message| %>
				<div class="row">
					<div class="col-md-2"><%= message.tag_number %></div>
					<div class="col-md-10"><%= wrap(message.content) %> </div>
				</div>
				<div class="row">
					<div class="col-md-12">
						Sent in by <%= message.user.first_name %> <%= message.user.last_initial %>. <%= time_ago_in_words(message.created_at) %> ago.
						<% if current_user?(message.user) %>
						 | <%= link_to "delete", message, method: :delete, data: { confirm: "You sure?" }, title: message.content %>
						<% end %>
					</div>
				</div>
				<hr>
			<% end %>
		<% end %>
		<h3>Received Messages</h3>
		<% if @received_messages.count == 0 %>
			<% if @user.tags.count == 0 %>
				You have to add your license plates! Look under My Tags on this page.
			<% else %>
				No one has sent you a message -- yet. Check back in a couple days.
			<% end %>
		<% else %>
			<% @received_messages.each do |message| %>
				<div class="row">
					<div class="col-md-2"><%= message.tag_number %></div>
					<div class="col-md-10"><%= wrap(message.content) %> </div>
				</div>
				<div class="row">
					<div class="col-md-12">
						Sent in by <%= message.user.first_name %> <%= message.user.last_initial %>. <%= time_ago_in_words(message.created_at) %> ago.
						<%# TODO: Ask Jordan if he thinks we should add the functionality to be able to delete received messages %>
					</div>
				</div>
				<hr>
			<% end %>
		<% end %>
	</div>
</div>