config/routes.rb
Tagenger::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :tags, only: [:create, :destroy]
  resources :users do
    resources :tags do
      member do
        delete :remove_user_tag
      end
    end
  end

  root to: 'users#new'
  #'/ui' to: 'ui#index'   # This was causing a redirect loop on Heroku

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new', 		via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/faq',     to: 'static_pages#faq', via: 'get'
  match '/submit',  to: 'messages#new',     via: 'get'

  # UI routes
  match '/ui',      to: 'ui#index',         via: 'get'
  get 'ui(/:action)', controller: 'ui'
  
end

app/views/layouts/_header.html.erb
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-example">
        <div class="navbar navbar-default newnav">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Tagenger', root_path, class: "navbar-brand brand" %>
          </div>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "FAQ", faq_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Submit", submit_path %></li>
                <!-- TODO: Add test for the visibility + what happens when visiting Users not as admin -->
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "Users", users_path %></li>
                <% end %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
              <% end %>
                
            </ul>
            <!-- <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Link</a></li>
            </ul> -->
          </div><!-- /.nav-collapse -->
        </div><!-- /.navbar -->
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

		<% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>

</body>
</html>